# Bos display server config

[general]
outer_gap = 8
inner_gap = 8
border_size = 2

[colors]
border_focused   = #8aadf4
border_unfocused = #363a4f
bg_top           = #1e3a5f
bg_bottom        = #0a0a0f

# [window_rules]
# hello_egui = float
# bouncing_cube_1 = tile
