# Bos network configuration

[general]
# mode = dhcp | static
mode = dhcp

[static]
# Used only when mode = static
address  = 10.0.2.15/24
gateway  = 10.0.2.2
dns      = 10.0.2.3

[ping]
# Send a test ping to the gateway on startup
enabled = true
